name: Django Docker CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and Run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d

    - name: Wait for services to be healthy
      run: |
        sleep 10

    - name: Run Migrations
      run: |
        docker-compose exec web python manage.py migrate

    - name: Run Tests
      run: |
        docker-compose exec web python manage.py test

    - name: Shut down Docker Compose
      run: |
        docker-compose down
